services:
  - docker

install:
  - docker build -t debian .
  - "docker run -d -P -v ~/.ssh/id_rsa.pub:/authorized_keys:ro --name debian debian"
  - sleep 10

script:
  - docker ps | grep debian
  - docker exec debian dpkg -s ca-certificates
  - docker exec debian which cron
  - docker exec debian which curl
  - docker exec debian which git
  - docker exec debian which nano
  - docker exec debian which sshd
  - docker exec debian ps aux | grep sshd
  - "PORT=$(docker inspect --format='{{(index (index .NetworkSettings.Ports \"22/tcp\") 0).HostPort}}' debian)"
  - echo $PORT
  - ssh -p $PORT -o "StrictHostKeyChecking no" 127.0.0.1
  - ssh -p $PORT -t 127.0.0.1 "pwd"
  - docker exec debian which ssmtp
  - docker exec debian which supervisord
  - docker exec debian which unzip
  - docker exec debian which vim
  - docker exec debian which wget