services:
  - docker

install:
  - docker build -t debian .
  - docker run -d --name debian debian
  - sleep 10

script:
  - docker ps | grep debian
  - docker exec debian dpkg -s ca-certificates
  - docker exec debian which cron
  - docker exec debian which curl
  - docker exec debian which git
  - docker exec debian which nano
  - docker exec debian which sshd
  - docker exec debian ps aux | grep sshd
  - docker exec debian which ssmtp
  - docker exec debian which supervisord
  - docker exec debian which unzip
  - docker exec debian which vim
  - docker exec debian which wget