services:
  - docker

install:
  - docker build -t debian .
  - docker run -d --name debian debian
  - sleep 10

script:
  - docker ps | grep debian
  - docker exec debian dpkg -s ca-certificates
  - docker exec debian which cron
  - docker exec debian which curl
  - docker exec debian which git
  - docker exec debian which nano
  - docker exec debian which sshd
  - docker exec debian ps aux | grep sshd
  - ssh-keygen -f ~/.ssh/test_rsa -t rsa -N ''
  - docker cp ~/.ssh/test_rsa.pub debian:/root/.ssh/authorized_keys
  - docker exec debian cat <<EOF > /root/.ssh/authorized_keys \n$PUBLIC_KEY \nEOF
  - docker exec -ti debian cat /root/.ssh/authorized_keys
  - "PORT=$(docker inspect --format='{{(index (index .NetworkSettings.Ports \"22/tcp\") 0).HostPort}}' debian)"
  - ssh -p $PORT -o "StrictHostKeyChecking no" -t root@127.0.0.1 "pwd"
  - docker exec debian which ssmtp
  - docker exec debian which supervisord
  - docker exec debian which unzip
  - docker exec debian which vim
  - docker exec debian which wget